name: Unit Test

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    branches:
      - main
  pull_request:
    # File paths to consider in the event. Optional; defaults to all.
    paths:
      - 'knowhere/**'
      - 'unittest/**'
      - 'thirdparty/**'
      - 'build/**'
      - 'build-support/**'
      - 'cmake/**'
      - '.github/workflows/ut.yaml'
      - 'build.sh'
      - 'CMakeLists.txt'
      - 'Makefile'
      - '!**.md'

jobs:
  ut:
    name: Unit Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-18.04, macos-11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependency
        run: |
          ./scripts/install_deps.sh
      - name: Run Unittest
        run: |
          ./build.sh -t Release -u && cmake_build/unittest/test_knowhere
  ut-msys:
    name: Unit Test on MSYS
    runs-on: windows-2019
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Toolchain
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
      - name: Install Dependency
        shell: msys2 {0}
        run: |
          ./scripts/install_deps.sh
      - name: Run Unittest
        shell: msys2 {0}
        run: |
          ./build.sh -t Release -u
          cp -fr output/bin/*.dll output/unittest/
          cp -fr output/lib/*.dll output/unittest/
          ./output/unittest/test_knowhere
